# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_providers {
        cloudinit = {
          source = "hashicorp/cloudinit"
          version = "2.3.3"
        }
        local = {
          source = "hashicorp/local"
          version = "2.4.1"
        }
      }
    }
